### ISSUE TITLE
How to add in DF

### ISSUE THREAD

**Issue by xxxHEKETOSxxx** [aticio/renko#6]
Greetings. Interested in your implementation of "RENKO" in python.. There is one question: How to add all this data to the Dataframe??

**Comment by aticio** [comment]
Hi,

I didn't use pandas so as not to make the output dependent on a specific library. So the output will be like:

```
{'type': 'up', 'open': 42500.87, 'close': 43248.87, 'low': 41679.74}
{'type': 'down', 'open': 42500.87, 'close': 41752.87}
{'type': 'down', 'open': 41752.87, 'close': 41004.87}
{'type': 'down', 'open': 41004.87, 'close': 40256.87}
```

However, if you want to put the data of bricks into a Dataframe, you can manually read this json (rnk.bricks):

```
rnk = Renko(1000, close)
rnk.create_renko()
print(rnk.bricks)
```

then you can put this data manueally to a Dataframe.

Please let me know if you have any further questions.

Thanks.
